# Site settings
title: "Mẹo Vặt Đời Sống"
url-title: "Mẹo Vặt Đời Sống"
description: "mẹo vặt gia đình, mẹo vặt hàng ngày, mẹo vặt nhân gian."
paginate: 100
url: "https://minhyeunhaudue.site"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
